// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp4s6EzwfuHfSk_o9bgPTBamWYxxyhqXE',
    appId: '1:661092054078:android:a40990a2b2a87c0f3d4d6f',
    messagingSenderId: '661092054078',
    projectId: 'quicktalk-f7ed5',
    storageBucket: 'quicktalk-f7ed5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWwKr69f2qwUPs4ioCyGmf3kKWNlGBkhA',
    appId: '1:661092054078:ios:5b2db0e31cf5f3dd3d4d6f',
    messagingSenderId: '661092054078',
    projectId: 'quicktalk-f7ed5',
    storageBucket: 'quicktalk-f7ed5.appspot.com',
    iosBundleId: 'com.example.quicktalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWwKr69f2qwUPs4ioCyGmf3kKWNlGBkhA',
    appId: '1:661092054078:ios:5b2db0e31cf5f3dd3d4d6f',
    messagingSenderId: '661092054078',
    projectId: 'quicktalk-f7ed5',
    storageBucket: 'quicktalk-f7ed5.appspot.com',
    iosBundleId: 'com.example.quicktalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhRyHw4uFvDtn6r07uvzm_PPOXPqxwsdA',
    appId: '1:661092054078:web:093a4d8731a574fc3d4d6f',
    messagingSenderId: '661092054078',
    projectId: 'quicktalk-f7ed5',
    authDomain: 'quicktalk-f7ed5.firebaseapp.com',
    storageBucket: 'quicktalk-f7ed5.appspot.com',
  );

}